---
minify: no
cdn: 
    path: C:\Work\community\assetoolz\test_data\results\www
    url: http://static-dn.tiwri-dev.com:8008
html:
    source: C:\Work\community\assetoolz\test_data\assets\html
    target: C:\Work\community\assetoolz\test_data\results\templates
stylesheets:
    source: C:\Work\community\assetoolz\test_data\assets\stylesheets
    target: C:\Work\community\assetoolz\test_data\results\www\stylesheets
scripts:
    source: C:\Work\community\assetoolz\test_data\assets\scripts
    target: C:\Work\community\assetoolz\test_data\results\www\scripts
images:
    source: C:\Work\community\assetoolz\test_data\assets\images
    target: C:\Work\community\assetoolz\test_data\results\www\images
config: C:\Work\community\assetoolz\test_data\appconf
i18n: C:\Work\community\assetoolz\test_data\assets\i18n
cache: C:\Work\community\assetoolz\test_data\assets\build
yuicompressor_file: C:\Work\community\assetoolz\test_data\assets\tools\yuicompressor-2.4.7.jar
htmlcompressor_file: C:\Work\community\assetoolz\test_data\assets\tools\htmlcompressor-1.5.3.jar